theme: jekyll-theme-minimal
title: <p style="text-align:center;color:black;" 
logo: img/WhatsApp Image 2020-07-15 at 10.43.00 PM.jpeg
description: <p style="text-align:center;color:black;" class="view">AI LEARNING ENGINEER<br></p>
google_analytics: "UA-167412463-1"

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script data-ad-client="ca-pub-4079358732644855" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "{{site.google_ad_client}}",
    enable_page_level_ads: true
  });
<script data-ad-client="ca-pub-4079358732644855" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
</script>
