theme: jekyll-theme-minimal
title: <p style="text-align:center;color:black;" 
logo: img/WhatsApp Image 2020-07-15 at 10.43.00 PM.jpeg
description: <p style="text-align:center;color:black;" class="view">AI LEARNING ENGINEER<br></p>
google_analytics: "UA-167412463-1"

