


theme: jekyll-theme-minimal
title: <p style="text-align:center;color:black;" class="view">AMAN <br></p>
logo: img/ai.png
description: <p style="text-align:center;color:black;" class="view">AI LEARNING ENGINEER<br></p>
google_analytics: "UA-167412463-1"
