theme: jekyll-theme-cayman

# THEME-SPECIFIC CONFIGURATION
title: AMAN
description: "A Learning Engineer"
show_downloads: "false"
google_analytics: "UA-167412463-1"


 # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
